// Generated by LiveScript 1.5.0
/**
 * @package   noise-c.wasm
 * @author    Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright Copyright (c) 2017, Nazar Mokrynskyi
 * @license   MIT License, see license.txt
 */
(function(){
  mergeInto(LibraryManager.library, {
    noise_rand_bytes: function(offset, size){
      var randombytes;
      randombytes = require('./src/randombytes');
      HEAPU8.set(randombytes(size), offset);
    }
  });
}).call(this);
