// Generated by LiveScript 1.5.0
/**
 * @package noise-c.wasm
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  mergeInto(LibraryManager.library, {
    noise_rand_bytes: function(offset, size){
      HEAPU8.set(Module['_random_bytes'](size), offset);
    }
  });
}).call(this);
